[workspace]
members = [
    "contracts/swap-order-lock-script",
    "contracts/liquidity-lock-script",
    "contracts/info-type-script",
    "contracts/info-lock-script",
    "share"
]

[profile.release]
overflow-checks = true
opt-level = 's'
lto = true
codegen-units = 1
panic = 'abort'
